schema_version: 1

context:
  version: "0.2.0"

package:
  name: advect
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/advect/advect-${{ version }}.tar.gz
  sha256: 5e32a63d2809bb9bb9f069f4ba3601be38ceb44649a96e564b92d4162eefb80d

build:
  number: 1
  skip:
    - match(python, '<3.12')
    - match(python, '>=3.15')
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1.12,<2
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1.12,<2
  run:
    - python
    - array-api-compat >=1.11.2,<2
    - numpy >=2.0,<2.6

tests:
  - python:
      imports:
        - advect
      pip_check: true
  - script:
      - 'python -c "import advect as ad; import numpy as np; np.testing.assert_allclose(ad.grad(lambda x: np.sum(x**2))(np.array([1.0, 2.0])), [2.0, 4.0])"'

about:
  homepage: https://yaugenst.github.io/advect/
  repository: https://github.com/yaugenst/advect
  documentation: https://yaugenst.github.io/advect/
  summary: Automatic differentiation for the NumPy code you already write
  license: MIT
  license_file:
    - LICENSE
    - RUST_STDLIB_COPYRIGHT.html
    - RUST_STDLIB_LICENSE_MIT.txt
    - RUST_STDLIB_LICENSE_UNICODE_3_0.txt
    - THIRD_PARTY_LICENSES.txt
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - yaugenst
